/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auditoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bitacora de auditoria
         * @description Bitacora de solo escritura, restringida al perfil Auditor.
         *
         *     Cada registro contiene el identificador de la corrida, el usuario
         *     responsable, la marca de tiempo, la accion y, ante modificacion de
         *     insumos o parametros, los valores anterior y posterior.
         *
         *     Las entradas van encadenadas: cada una incluye el resumen de la anterior,
         *     de modo que suprimir una intermedia rompe la cadena y se detecta.
         */
        get: operations["auditoria_api_auditoria_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar casos */
        get: operations["listar_api_casos_get"];
        put?: never;
        /**
         * Crear o duplicar un caso
         * @description Crea un caso en estado borrador.
         *
         *     Con `duplicar_de`, copia los insumos de un caso existente. El duplicado
         *     nace en borrador y con revision de inputs 1: es un caso nuevo, no una
         *     version del anterior.
         */
        post: operations["crear_api_casos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de un caso
         * @description Incluye las acciones disponibles para el perfil del solicitante.
         */
        get: operations["detalle_api_casos__id_caso__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/comparar/{id_otro}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comparar dos casos
         * @description Compara el caso sin proyecto contra uno o varios casos con proyecto.
         *
         *     Advierte cuando las corridas no son comparables: contrastar un caso base
         *     calculado con una version mayor del motor contra otro calculado con una
         *     version mayor distinta produce una diferencia que no es atribuible al
         *     proyecto.
         */
        get: operations["comparar_api_casos__id_caso__comparar__id_otro__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/congelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Congelar la evaluación como sustento de decisión
         * @description Transición irreversible.
         *
         *     Genera una imagen sellada autocontenida —inputs, parámetros efectivamente
         *     utilizados, versión del motor, resultados y documentación de respaldo—,
         *     la resume con SHA-256 y la deposita en el contenedor con política de
         *     inmutabilidad.
         *
         *     Desde ese momento la evaluación no puede alterarse. Para ver el efecto de
         *     un cambio posterior del modelo, se recalcula: eso genera una corrida
         *     nueva y deja esta intacta como sustento.
         *
         *     Congelar corresponde a quien sustenta la decisión, no a quien opera la
         *     plataforma. Por eso el Ingeniero de Proyecto no aparece entre los
         *     perfiles autorizados.
         */
        post: operations["congelar_api_casos__id_caso__congelar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/corrida/bloques": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bloques intermedios de la última corrida, en el orden del libro
         * @description Toda la cadena de cálculo, hoja por hoja, como la presenta el libro.
         *
         *     Verificar solo el indicador final es metodológicamente inválido: dos
         *     errores que se compensan producen un NPV correcto sobre un modelo roto.
         *     Este endpoint es lo que permite recorrer la cadena entera en pantalla y
         *     localizar una diferencia en la línea donde aparece.
         */
        get: operations["bloques_de_la_corrida_api_casos__id_caso__corrida_bloques_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/evaluar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ejecutar la evaluación económica
         * @description Calcula la evaluación y deja la corrida en estado *calculada*.
         *
         *     Registra la terna de versiones con la que se calculó. Una corrida no
         *     guarda una referencia a la versión vigente del motor: guarda la versión
         *     exacta, para que publicar una versión nueva no altere corridas previas.
         */
        post: operations["evaluar_api_casos__id_caso__evaluar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/exportar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exportar el tablero y los estados a Excel o PDF
         * @description Genera el reporte y devuelve una URL temporal de lectura.
         *
         *     El archivo se descarga directamente del almacenamiento, por el mismo
         *     mecanismo de firma que usa la carga: no atraviesa la puerta de enlace.
         *
         *     Con `destino=sharepoint` publica ademas en la biblioteca documental del
         *     proyecto. Si el sitio aun no esta habilitado (R-44), la exportacion se
         *     completa y `url_sharepoint` queda vacia: es una limitacion de
         *     habilitacion, no un defecto de la plataforma.
         *
         *     Es la cuarta de las cinco comprobaciones obligatorias del pase.
         */
        get: operations["exportar_api_casos__id_caso__exportar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/plantillas/autorizacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autorizar la carga directa de una plantilla
         * @description Emite una firma de acceso compartido acotada a un solo archivo.
         *
         *     Cinco restricciones sostienen la seguridad del mecanismo:
         *
         *     - Firma de **delegación de usuario**, no clave de cuenta. El
         *       almacenamiento tiene deshabilitado el acceso por clave compartida: no
         *       existe clave que firmar.
         *     - Vigencia de quince minutos.
         *     - Permiso acotado a **un blob concreto**, no al contenedor.
         *     - Escritura y creación, sin lectura: quien carga no puede leer lo que ya
         *       existe.
         *     - **El nombre del blob lo determina el servidor.** Aceptar una ruta del
         *       cliente permitiría escribir sobre la plantilla de otra evaluación.
         */
        post: operations["autorizar_carga_api_casos__id_caso__plantillas_autorizacion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/plantillas/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar y validar una plantilla cargada
         * @description Comprueba que el archivo llegó y lo valida antes de admitirlo.
         *
         *     La validación de estructura, unidades, clasificaciones y horizonte
         *     temporal depende de las plantillas definitivas que elabora MINSUR
         *     (`R-07`). INVA implementa su lectura y validación, no su diseño.
         */
        post: operations["confirmar_carga_api_casos__id_caso__plantillas_confirmar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/recalcular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recalcular una corrida congelada con el motor vigente
         * @description Crea una corrida nueva a partir de una congelada. **No la modifica.**
         *
         *     Es la forma de observar el efecto de un cambio del modelo sin que la
         *     evidencia que sustentó una decisión deje de existir. La corrida nueva
         *     apunta a la anterior como origen.
         */
        post: operations["recalcular_api_casos__id_caso__recalcular_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/casos/{id_caso}/verificar-fidelidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contrastar contra el modelo de referencia
         * @description Contraste en los cuatro niveles.
         *
         *     | Nivel | Objeto | Criterio |
         *     |---|---|---|
         *     | N0 | Paridad de inputs | Coincidencia exacta |
         *     | N1 | Bloques intermedios, año a año | 0,1 % o US$ 10 000 por línea |
         *     | N2 | Flujos, año a año | 0,1 % o US$ 10 000 por año |
         *     | N3 | Indicadores finales | NPV 0,1 % · TIR 5 pb · Payback 0,1 año |
         *
         *     Verificar solo el indicador final es metodológicamente insuficiente: dos
         *     errores compensatorios en bloques intermedios producen un NPV correcto
         *     sobre un modelo inválido.
         *
         *     Los umbrales son la propuesta de INVA; el valor contractual lo fija
         *     Finanzas (`R-31`). Este endpoint es el que consulta la segunda de las
         *     cinco comprobaciones obligatorias de la ventana de pase.
         */
        get: operations["verificar_fidelidad_api_casos__id_caso__verificar_fidelidad_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/estados-financieros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estados financieros estimados, auditables linea por linea
         * @description Cada linea con un valor por ano del horizonte detectado.
         *
         *     La auditabilidad linea por linea es lo que permite localizar una
         *     discrepancia contra el modelo de referencia en el bloque que la origina,
         *     y no solo constatar que el indicador final difiere.
         */
        get: operations["estados_financieros_api_estados_financieros_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/historial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historial de evaluaciones
         * @description Corridas ordenadas de la mas reciente a la mas antigua.
         *
         *     Cada entrada incluye la version del motor con la que se calculo, no la
         *     vigente: es lo que permite entender por que dos corridas del mismo caso
         *     dan distinto.
         *
         *     Es la quinta de las cinco comprobaciones obligatorias del pase.
         */
        get: operations["historial_api_historial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio */
        get: operations["salud_api_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tablero": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Indicadores, cascada y curvas del caso
         * @description Apertura comprometida por debajo de cinco segundos.
         *
         *     Es la tercera de las cinco comprobaciones obligatorias de la ventana de
         *     pase, que mide esa latencia contra el objetivo del alcance.
         */
        get: operations["tablero_api_tablero_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuario autenticado
         * @description Identidad y alcance del usuario.
         *
         *     La interfaz la consulta al iniciar sesión para decidir qué controles
         *     muestra. Que un control no aparezca no sustituye a la verificación del
         *     servidor, que ocurre en cada operación.
         */
        get: operations["yo_api_yo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Accion
         * @enum {string}
         */
        Accion: "ejecutar" | "editar-insumos" | "congelar" | "recalcular";
        /**
         * AutorizacionCarga
         * @description Permiso temporal para escribir un blob concreto.
         *
         *     El archivo se sube directamente al almacenamiento con esta URL. No
         *     atraviesa la puerta de enlace ni los servicios de aplicación.
         */
        AutorizacionCarga: {
            /**
             * Encabezados
             * @description Encabezados obligatorios de la solicitud de subida
             */
            encabezados?: {
                [key: string]: string;
            };
            /**
             * Expira
             * Format: date-time
             */
            expira: string;
            /**
             * Metodo
             * @default PUT
             * @constant
             */
            metodo: "PUT";
            /**
             * Ruta Blob
             * @description Ruta que debe confirmarse tras la subida
             */
            ruta_blob: string;
            /**
             * Url
             * @description URL con firma de acceso compartido
             */
            url: string;
        };
        /**
         * BloqueDeCorrida
         * @description Un bloque del cálculo, correspondiente a una hoja del libro.
         */
        BloqueDeCorrida: {
            /** Clave */
            clave: string;
            /**
             * Hoja
             * @description Hoja del libro corporativo que reproduce este bloque
             */
            hoja: string;
            /** Series */
            series: components["schemas"]["SerieAnual"][];
            /** Titulo */
            titulo: string;
        };
        /**
         * BloquesDeCorrida
         * @description La cadena de cálculo entera, en el orden en que la presenta el libro.
         */
        BloquesDeCorrida: {
            /** Anios */
            anios: number[];
            /** Bloques */
            bloques: components["schemas"]["BloqueDeCorrida"][];
            /**
             * Campos Con Dato
             * @description Campos con algún valor distinto de cero, por unidad. Lo decide el motor para que la API y la interfaz oculten las mismas filas del mismo caso
             */
            campos_con_dato?: {
                [key: string]: string[];
            };
            /** Discrepancias */
            discrepancias?: components["schemas"]["DiscrepanciaDeCorroboracion"][];
            /** Id Caso */
            id_caso: string;
            /** Id Corrida */
            id_corrida: string;
            /** Unidades */
            unidades: string[];
        };
        /** ConfirmacionCarga */
        ConfirmacionCarga: {
            /** Ruta Blob */
            ruta_blob: string;
        };
        /** CorridaCongelada */
        CorridaCongelada: {
            /**
             * Congelada En
             * Format: date-time
             */
            congelada_en: string;
            /** Congelada Por */
            congelada_por: string;
            /** Huella Contenido */
            huella_contenido: string;
            /** Huella Sello */
            huella_sello: string;
            /** Id Corrida */
            id_corrida: string;
            /**
             * Ruta Imagen
             * @description Ubicación de la imagen sellada
             */
            ruta_imagen: string;
        };
        /** DesviacionLinea */
        DesviacionLinea: {
            /** Anio */
            anio?: number | null;
            /** Dentro De Tolerancia */
            dentro_de_tolerancia: boolean;
            /** Diferencia Relativa */
            diferencia_relativa: number;
            /** Linea */
            linea: string;
            /** Valor Plataforma */
            valor_plataforma: number;
            /** Valor Referencia */
            valor_referencia: number;
        };
        /** DetalleCaso */
        DetalleCaso: {
            /**
             * Abreviatura
             * @description Nombre corto del escenario, para tablas y comparaciones
             * @default
             */
            abreviatura: string;
            /** Acciones Disponibles */
            acciones_disponibles: components["schemas"]["Accion"][];
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Actualizado Por */
            actualizado_por: string;
            /** Descripcion */
            descripcion: string;
            estado: components["schemas"]["Estado"];
            /** Id Caso */
            id_caso: string;
            /** Nombre */
            nombre: string;
            /** @description Presente solo si el caso tiene una corrida */
            terna?: components["schemas"]["Terna"] | null;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "sin-proyecto" | "con-proyecto";
        };
        /**
         * DiscrepanciaDeCorroboracion
         * @description Una celda donde el dato cargado y el recálculo del sistema no coinciden.
         *
         *     No detiene el cálculo ni sustituye el dato: el que manda es el del usuario.
         *     Es control de calidad, y viaja con la corrida para poder sustentar después
         *     por qué se aceptó una diferencia.
         */
        DiscrepanciaDeCorroboracion: {
            /** Ano */
            ano: number;
            /** Cargado */
            cargado: number;
            /** Concepto */
            concepto: string;
            /** Diferencia */
            diferencia: number;
            /** Diferencia Relativa */
            diferencia_relativa: number;
            /** Recalculado */
            recalculado: number;
            /** Unidad */
            unidad: string;
        };
        /** EntradaHistorial */
        EntradaHistorial: {
            estado: components["schemas"]["Estado"];
            /** Id Caso */
            id_caso: string;
            /** Id Corrida */
            id_corrida: string;
            /**
             * Marca Tiempo
             * Format: date-time
             */
            marca_tiempo: string;
            /** Nombre Caso */
            nombre_caso: string;
            /** Npv Musd */
            npv_musd?: number | null;
            /** Usuario */
            usuario: string;
            /** Version Motor */
            version_motor: string;
        };
        /**
         * Estado
         * @enum {string}
         */
        Estado: "borrador" | "calculada" | "congelada";
        /**
         * EstadosFinancieros
         * @description Estados estimados, auditables línea por línea.
         */
        EstadosFinancieros: {
            /** Anios */
            anios: number[];
            /** Id Caso */
            id_caso: string;
            /**
             * Lineas
             * @description Cada línea del estado, con un valor por año del horizonte
             */
            lineas: {
                [key: string]: number[];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IncidenciaDePlantilla
         * @description Un problema de lectura, con su ubicación exacta en el libro.
         *
         *     La ingesta acumula incidencias y no se detiene en la primera, porque una
         *     plantilla llenada a mano llega con varias a la vez. Los tres campos van
         *     separados para que la interfaz pueda llevar al usuario a la celda: una
         *     cadena ya compuesta obliga a que la pantalla la desarme para eso.
         */
        IncidenciaDePlantilla: {
            /**
             * Celda
             * @description Referencia de celda, o `-` si el problema es del libro
             */
            celda: string;
            /**
             * Hoja
             * @description Pestaña del libro, o `(archivo)` y `(libro)`
             */
            hoja: string;
            /** Mensaje */
            mensaje: string;
        };
        /**
         * Indicadores
         * @description Los cuatro indicadores del contraste N3.
         *
         *     `tir` y `capital_intensity` son opcionales porque el caso puede no
         *     definirlas, y eso es un resultado correcto, no un fallo. Un caso que abre
         *     en positivo —una operación en marcha— no tiene una tasa que describa su
         *     rentabilidad, y el libro escribe un guion en esa celda. Devolver cero en su
         *     lugar haría indistinguible «no hay TIR» de «TIR igual a cero», que es
         *     justamente la distinción que fija el ADR 0011.
         */
        Indicadores: {
            /**
             * Capital Intensity
             * @description Dólares de capital por tonelada de capacidad, o nula si no hay capacidad
             */
            capital_intensity?: number | null;
            /**
             * Npv Musd
             * @description Valor actual neto, millones de dólares
             */
            npv_musd: number;
            /** Payback Anios */
            payback_anios: number;
            /**
             * Tir
             * @description Tasa interna de retorno en tanto por uno, o nula si el caso no la define
             */
            tir?: number | null;
        };
        /** NuevoCaso */
        NuevoCaso: {
            /**
             * Abreviatura
             * @description Nombre corto con el que el escenario aparece en tablas, leyendas y comparaciones, donde el nombre completo no cabe
             * @example SD Fase III
             */
            abreviatura: string;
            /**
             * Descripcion
             * @default
             */
            descripcion: string;
            /**
             * Duplicar De
             * @description Identificador del caso a duplicar. El duplicado nace en borrador
             */
            duplicar_de?: string | null;
            /** Nombre */
            nombre: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "sin-proyecto" | "con-proyecto";
        };
        /** PaginaHistorial */
        PaginaHistorial: {
            /** Continuacion */
            continuacion?: string | null;
            /** Corridas */
            corridas: components["schemas"]["EntradaHistorial"][];
            /** Total */
            total: number;
        };
        /**
         * Perfil
         * @description Los seis perfiles del alcance.
         * @enum {string}
         */
        Perfil: "administrador" | "finanzas" | "lider-de-estudio" | "ingeniero-de-proyecto" | "consulta-ejecutiva" | "auditor";
        /**
         * Problema
         * @description Cuerpo de error. Explica qué pasó y cómo resolverlo.
         */
        Problema: {
            /** Detalle */
            detalle: string;
            /**
             * Restriccion
             * @description Restricción del cuadro de control que bloquea, si aplica
             */
            restriccion?: string | null;
        };
        /** ResultadoEvaluacion */
        ResultadoEvaluacion: {
            /** Duracion Ms */
            duracion_ms: number;
            /**
             * Ejecutada En
             * Format: date-time
             */
            ejecutada_en: string;
            /** Ejecutada Por */
            ejecutada_por: string;
            estado: components["schemas"]["Estado"];
            /** Id Caso */
            id_caso: string;
            /** Id Corrida */
            id_corrida: string;
            indicadores: components["schemas"]["Indicadores"];
            terna: components["schemas"]["Terna"];
        };
        /** ResultadoExportacion */
        ResultadoExportacion: {
            /**
             * Expira
             * Format: date-time
             */
            expira: string;
            /**
             * Formato
             * @enum {string}
             */
            formato: "xlsx" | "pdf";
            /**
             * Url Descarga
             * @description URL temporal de lectura
             */
            url_descarga: string;
            /**
             * Url Sharepoint
             * @description Presente si el sitio de SharePoint está habilitado (R-44)
             */
            url_sharepoint?: string | null;
        };
        /**
         * ResultadoFidelidad
         * @description Contraste contra el modelo de referencia en los cuatro niveles.
         */
        ResultadoFidelidad: {
            /** Dentro De Tolerancia */
            dentro_de_tolerancia: boolean;
            /** Desviaciones */
            desviaciones?: components["schemas"]["DesviacionLinea"][];
            /** Id Caso */
            id_caso: string;
            /**
             * Nivel N0
             * @description Paridad de inputs, sin tolerancia
             */
            nivel_n0: boolean;
            /**
             * Nivel N1
             * @description Bloques intermedios, año a año
             */
            nivel_n1: boolean;
            /**
             * Nivel N2
             * @description Flujos, año a año
             */
            nivel_n2: boolean;
            /**
             * Nivel N3
             * @description Indicadores finales
             */
            nivel_n3: boolean;
            /** Version Motor */
            version_motor: string;
        };
        /**
         * ResultadoValidacion
         * @description Validación de una plantilla antes de admitirla al cálculo.
         */
        ResultadoValidacion: {
            /** Filas Leidas */
            filas_leidas: number;
            /**
             * Hallazgos
             * @description Las mismas incidencias ya compuestas como texto, para registro
             */
            hallazgos?: string[];
            /**
             * Huella
             * @description SHA-256 del contenido admitido
             * @default
             */
            huella: string;
            /**
             * Incidencias
             * @description Problemas encontrados, con su hoja y su celda
             */
            incidencias?: components["schemas"]["IncidenciaDePlantilla"][];
            /** Valida */
            valida: boolean;
        };
        /** ResumenCaso */
        ResumenCaso: {
            /**
             * Abreviatura
             * @description Nombre corto del escenario, para tablas y comparaciones
             * @default
             */
            abreviatura: string;
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
            /** Actualizado Por */
            actualizado_por: string;
            estado: components["schemas"]["Estado"];
            /** Id Caso */
            id_caso: string;
            /** Nombre */
            nombre: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "sin-proyecto" | "con-proyecto";
        };
        /** Salud */
        Salud: {
            /** Entorno */
            entorno: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "ok" | "degradado";
            /** Version Api */
            version_api: string;
            /** Version Motor */
            version_motor?: string | null;
        };
        /**
         * SerieAnual
         * @description Una línea del libro, con un valor por año del horizonte.
         */
        SerieAnual: {
            /** Concepto */
            concepto: string;
            /**
             * Origen
             * @description Si la línea la carga el usuario o la produce el motor
             * @default calculada
             * @enum {string}
             */
            origen: "dato" | "calculada";
            /**
             * Recalculada
             * @description Lo que el sistema esperaba para una línea que el usuario carga y el motor sabe rehacer. Va debajo de la cargada; sin ella la alerta no dice qué esperaba
             */
            recalculada?: number[] | null;
            /**
             * Unidad
             * @description Unidad productiva a la que pertenece la línea, si no es del caso entero
             */
            unidad?: string | null;
            /** Valores */
            valores: number[];
        };
        /**
         * SolicitudCarga
         * @description Petición de autorización para subir una plantilla.
         */
        SolicitudCarga: {
            /**
             * Nombre Archivo
             * @description Nombre original. Se usa para validar la extensión, no para la ruta
             */
            nombre_archivo: string;
            /** Tamanio Bytes */
            tamanio_bytes: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "produccion" | "capex" | "opex";
        };
        /** SolicitudCongelamiento */
        SolicitudCongelamiento: {
            /**
             * Motivo
             * @description Qué decisión sustenta esta evaluación. Es lo que explica, años después, por qué se congeló
             */
            motivo: string;
            /**
             * Rutas Respaldo
             * @description Documentos y correos de aprobación asociados
             */
            rutas_respaldo?: string[];
        };
        /** Tablero */
        Tablero: {
            /** Capex Por Etapa */
            capex_por_etapa?: {
                [key: string]: unknown;
            }[];
            /** Cascada */
            cascada?: {
                [key: string]: unknown;
            }[];
            /** Curva Costo Unitario */
            curva_costo_unitario?: {
                [key: string]: unknown;
            }[];
            /** Curva Produccion */
            curva_produccion?: {
                [key: string]: unknown;
            }[];
            /** Id Caso */
            id_caso: string;
            indicadores: components["schemas"]["Indicadores"];
        };
        /**
         * Terna
         * @description Las tres versiones que definen una corrida.
         */
        Terna: {
            /**
             * Datos Maestros
             * @description Comité de Precios utilizado
             * @example CP-2026-03
             */
            datos_maestros: string;
            /** Huella Inputs */
            huella_inputs: string;
            /**
             * Motor
             * @description Versión del motor de cálculo
             * @example 1.2.0
             */
            motor: string;
            /** Revision Inputs */
            revision_inputs: number;
            /**
             * Vigencia Datos Maestros
             * Format: date
             */
            vigencia_datos_maestros: string;
        };
        /**
         * UsuarioActual
         * @description Identidad y alcance del usuario autenticado.
         */
        UsuarioActual: {
            /**
             * Acciones Permitidas
             * @description Operaciones que el perfil puede ejecutar en la plataforma
             */
            acciones_permitidas?: string[];
            /** Correo */
            correo: string;
            /**
             * Id Objeto
             * @description Identificador de objeto en Entra ID
             */
            id_objeto: string;
            /** Nombre */
            nombre: string;
            /** @description Perfil derivado de la pertenencia a grupos */
            perfil: components["schemas"]["Perfil"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auditoria_api_auditoria_get: {
        parameters: {
            query?: {
                caso?: string | null;
                corrida?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    listar_api_casos_get: {
        parameters: {
            query?: {
                /** @description Filtra por tipo de caso */
                tipo?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumenCaso"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_api_casos_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NuevoCaso"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleCaso"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_api_casos__id_caso__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetalleCaso"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    comparar_api_casos__id_caso__comparar__id_otro__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                id_caso: string;
                id_otro: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    congelar_api_casos__id_caso__congelar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                /** @description Identificador del caso */
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudCongelamiento"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorridaCongelada"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    bloques_de_la_corrida_api_casos__id_caso__corrida_bloques_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                /** @description Identificador del caso */
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BloquesDeCorrida"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluar_api_casos__id_caso__evaluar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                /** @description Identificador del caso */
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoEvaluacion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    exportar_api_casos__id_caso__exportar_get: {
        parameters: {
            query?: {
                destino?: string;
                formato?: string;
            };
            header?: {
                authorization?: string;
            };
            path: {
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoExportacion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    autorizar_carga_api_casos__id_caso__plantillas_autorizacion_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudCarga"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutorizacionCarga"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirmar_carga_api_casos__id_caso__plantillas_confirmar_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmacionCarga"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoValidacion"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    recalcular_api_casos__id_caso__recalcular_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                /** @description Identificador del caso */
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoEvaluacion"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verificar_fidelidad_api_casos__id_caso__verificar_fidelidad_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                /** @description Identificador del caso */
                id_caso: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoFidelidad"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    estados_financieros_api_estados_financieros_get: {
        parameters: {
            query?: {
                caso?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadosFinancieros"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    historial_api_historial_get: {
        parameters: {
            query?: {
                limite?: number;
                caso?: string | null;
                continuacion?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaHistorial"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    salud_api_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
        };
    };
    tablero_api_tablero_get: {
        parameters: {
            query?: {
                /** @description Caso a mostrar */
                caso?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tablero"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Not Implemented */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problema"];
                };
            };
        };
    };
    yo_api_yo_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioActual"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
